### ISSUE TITLE
[FileManager] _requestFileSystem causes "Fatal signal 11" using gist/cordova/android.

### ISSUE THREAD

**Issue by chasen** [photokandyStudios/YASMF-Next#2]
Im not sure why it throws a fatal error. and isnt caught.

**Comment by chasen** [comment]
This seems to fix the issue. Inside the function change:

```
var requestFileSystem = window.webkitRequestFileSystem || window.requestFileSystem;
```

To:

```
var requestFileSystem = window.requestFileSystem || window.webkitRequestFileSystem;
```

**Comment by kerrishotts** [comment]
Thanks. I'll update the gist. 

What version android?

**Comment by chasen** [comment]
4.2.2

**Comment by kerrishotts** [comment]
Hmm. Might be why I haven't caught it; my device is 4.4, and I've tested on 4.3 in the emulator. I'll have to look at earlier versions and see if they do funny things too.

**Comment by chasen** [comment]
Thanks, my tablet is a Galaxy tab 2 and it wont let me get 4.4 :(

**Comment by chasen** [comment]
I realize this likely isnt the place to ask this but do you happen to know why requestFileSystem doesnt always resolve for android? http://stackoverflow.com/questions/24050455/cordova-3-5-requestfilesystem-occasionally-failes-to-resolve-android-4-2-2

**Comment by kerrishotts** [comment]
Hrmm. I've heard of similar issues, but I've never experienced it directly (possibly because 4.4 may have fixed the issue?) I commented on the SO issue asking if it occurs when the File plugin is the only plugin being used -- just to rule out the possibility of other plugin interference.
